name: deep_collection
description: Extends [List], [Set] and [Map] in order to add commonly used recursive methods such as sorting, reversing, merging, finding intersections or differences.
version: 1.0.2
homepage: https://github.com/owczaro/deep_collection

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  effective_dart: ^1.3.2

dev_dependencies:
  test: ^1.17.12
